---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-4
  labels:
    app: service-4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-4
  template:
    metadata:
      labels:
        app: service-4
    spec:
      containers:
        - name: service-4
          image: service_4:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003

---
apiVersion: v1
kind: Service
metadata:
  name: service-4
spec:
  ports:
  - port: 5003
    protocol: TCP
    targetPort: 5003
  selector:
    app: service-4
  type: ClusterIP
